// Generated by scripts/parse-pdf.py from public/study-materials/pig-dissection.pdf.
// Edit the PDF (and re-run the script) rather than hand-editing this file.

export type Card = {
  id: string;
  front: string;
  back: string;
  hint?: string;
};

export type Deck = {
  id: string;
  title: string;
  description: string;
  cards: Card[];
};

export const pigAnatomyDeck: Deck = {
  id: "pig-anatomy",
  title: "Fetal Pig Dissection",
  description: "Terms and definitions extracted from the fetal pig dissection lab guide PDF.",
  cards: [
    {
      id: "anterior",
      front: "anterior",
      back: "towards the head",
    },
    {
      id: "posterior",
      front: "posterior",
      back: "towards the rear",
    },
    {
      id: "caudal",
      front: "caudal",
      back: "towards the tail",
    },
    {
      id: "dorsal",
      front: "dorsal",
      back: "towards the back; up",
    },
    {
      id: "ventral",
      front: "ventral",
      back: "towards the belly; down",
    },
    {
      id: "lateral",
      front: "lateral",
      back: "towards the side",
    },
    {
      id: "medial",
      front: "medial",
      back: "towards the middle",
    },
    {
      id: "proximal",
      front: "proximal",
      back: "close to a specified point of reference",
    },
    {
      id: "distal",
      front: "distal",
      back: "away from a specified point of reference",
    },
    {
      id: "pectoral",
      front: "pectoral",
      back: "referring to the shoulder region",
    },
    {
      id: "pelvic",
      front: "pelvic",
      back: "referring to the hip region",
    },
    {
      id: "thorax",
      front: "thorax",
      back: "L: anterior to the abdomen, separated from it by the diaphragm.\nF: houses and protects the major circulatory and respiratory organs, primarily the\nheart and lungs.",
    },
    {
      id: "abdomen",
      front: "abdomen",
      back: "L: in the lower trunk, starting just below the chest cavity (separated by the\ndiaphragm) and extending to the pelvic region.\nF: houses, protects, and supports the digestive, excretory, and reproductive organ\nsystems.",
    },
    {
      id: "ears",
      front: "ears",
      back: "F: allows the mammal to hear by collecting and funneling sound waves into the\near canal.",
    },
    {
      id: "pinna-aka-auricle",
      front: "pinna (aka auricle)",
      back: "L: external flap on the tip of the ears.\nF: it captures and focuses sound waves into the external auditory canal and the\nmiddle ear.\n**note: animals that depend on hearing for survival have bigger pinnas**",
    },
    {
      id: "eardrum-tympanic-membrane",
      front: "eardrum/tympanic membrane",
      back: "L: at the base of the external auditory canal, just inside the skull.\nF: it collects and transmits sound waves from the external environment to the\nbones of the middle ear.",
    },
    {
      id: "external-acoustic-meatus",
      front: "external acoustic meatus",
      back: "L: tube that begins at the base of the pinna and runs through the temporal bone\nto the tympanic membrane (eardrum)\nF: it collects and funnels sound waves toward the eardrum.",
    },
    {
      id: "eyes",
      front: "eyes",
      back: "F: detect light, focus it, and transmit visual signals to the brain, allowing the\nmammal to see.",
    },
    {
      id: "upper-eyelid",
      front: "upper eyelid",
      back: "L: directly above the eye of the fetal pig.\nF: protects the eye from physical damage, debris, and bright light, and also helps\nkeep the eyeball moist.",
    },
    {
      id: "lower-eyelid",
      front: "lower eyelid",
      back: "L: ventral (bottom) side of the eye.\nF: physically protects the eyeball from debris, external damage, and drying out,\npreventing tears from overflowing.",
    },
    {
      id: "nictitating-membrane",
      front: "nictitating membrane",
      back: "L: anterior portion of the eyeball;\nF: moves across the eyeball, helping to keep it clean. protects the eye, sweeps\ndebris from the cornea, and distributes tears to keep the eye moist without\ncompletely obstructing vision.",
    },
    {
      id: "mouth-oral-cavity",
      front: "mouth/oral cavity",
      back: "F: begins the digestive process by ingesting food through mechanical digestion\n(chewing) and chemical breakdown (saliva)",
    },
    {
      id: "lips",
      front: "lips",
      back: "L: fleshy folds that form the outer boundary of the mouth.\nF: grips food, and along with the cheeks, it helps the young suckle.\n**note: the arrow on the pic is not pointing to the mouth**",
    },
    {
      id: "cheeks",
      front: "cheeks",
      back: "L: lateral sides of the mouth.\nF: contain food within the mouth during chewing, and also along with the lips,\nhelp the young suckle.",
    },
    {
      id: "nostrils",
      front: "nostrils",
      back: "L: tip of the snout\nF: external openings for the respiratory system, allowing air to be drawn into the\nnasal cavity for respiration, olfaction (smell), and air filtration.",
    },
    {
      id: "legs",
      front: "legs",
      back: "F: support the body weight and provide locomotion/movement.\n**note: the pig is ungulate (hoofed) so it walks on tippy toes)**",
    },
    {
      id: "umbilical-cord",
      front: "umbilical cord",
      back: "L: belly surface\nF: allows for the transfer of oxygen and nutrients from the placenta to the embryo\nas well as waste products from the embryo to the placenta.",
    },
    {
      id: "nipples",
      front: "nipples",
      back: "L: ventral (belly) surface in parallel rows along either side of the umbilical cord.\nF: external opening of the mammary glands that secrete and release milk to nurse\noffspring.",
    },
    {
      id: "mammary-glands",
      front: "mammary glands",
      back: "F: produce and secrete milk to nourish newborn piglets.",
    },
    {
      id: "scrotal-sacs",
      front: "scrotal sacs",
      back: "L: at the posterior end of the body\nF: house, protect, and regulate the temperature of the testes.",
    },
    {
      id: "urogenital-opening",
      front: "urogenital opening",
      back: "L:\nmale: posterior to the umbilical cord (behind)\nfemale: ventral to the anus\nF:\nfemale: external exit point for urine from the excretory system and for the reproductive tract (vagina)\nmale: exit point for both urine and sperm.",
    },
    {
      id: "penis",
      front: "penis",
      back: "L: on the ventral (belly) side, posterior to the umbilical cord.\nF: shared passage for both the reproductive system (transmitting sperm) and the\nexcretory system (expelling urine)",
    },
    {
      id: "anus",
      front: "anus",
      back: "L: base of the tail\nF: exit point for the elimination of feces and digestive waste.",
    },
    {
      id: "tensor-fascia-lata",
      front: "tensor fascia lata",
      back: "L: anterior surface of thigh (origin= ilium, insertion= patella)\nF: responsible for extension and lateral rotation of knee and abduction and medial\nrotation of thigh at hip.",
    },
    {
      id: "gluteus-medius",
      front: "gluteus medius",
      back: "L: posterior to the preceding muscle (origin= vertebrae, insertion= proximal end\nof femur)\nF: abducts the thigh.",
    },
    {
      id: "gluteus-maximus",
      front: "gluteus maximus",
      back: "L: posterior to the gluteus medius (origin= sacral vertebrae, insertion= fascia)\nF: abducts the thigh.",
    },
    {
      id: "biceps-femoris",
      front: "biceps femoris",
      back: "L: triangular muscle on the posterior half of the lateral surface of the thigh (origin=\nischium, insertion= lower femur and upper tibia)\nF: abducts the thigh and flexes the shank.",
    },
    {
      id: "gastrocnemius",
      front: "gastrocnemius",
      back: "L: foot (origin= lower femur, insertion= achilles tendon into calcaneum)\nF: extends the foot.",
    },
    {
      id: "tibialis-anterior",
      front: "tibialis anterior",
      back: "L: most ventral (origin= upper tibia and fibula, insertion= tendon to metatarsals)\nF: flexes the foot.",
    },
    {
      id: "extensor-digitorum-longus",
      front: "extensor digitorum longus",
      back: "L: very close to the tibialis anterior (origin= lower femur, insertion= into a tendon\nwhich subdivided into four, one for each digit)\nF: extends the digits.",
    },
    {
      id: "tongue",
      front: "tongue",
      back: "L: ventral surface of the oral cavity.\nF: manipulates and moves food, aids in licking and swallowing, and has sensory\npapillae for taste.",
    },
    {
      id: "hard-palate",
      front: "hard palate",
      back: "L: dorsal surface of the oral cavity.\nF: separates the oral cavity from the nasal cavities.",
    },
    {
      id: "soft-palate",
      front: "soft palate",
      back: "L: posterior to the hard palate.\nF: closes off the nasal passage during swallowing, ensuring food and liquid travel\nsafely down the esophagus instead of into the nose.",
    },
    {
      id: "teeth",
      front: "teeth",
      back: "L: inside the mouth, upper and lower gums.\nF: help bite, tear, and grind food.",
    },
    {
      id: "incisors",
      front: "incisors",
      back: "L: anterior (front) regions of both the upper (maxilla) and lower (mandible) jaws.\nF: help bite, grasp and cut food.",
    },
    {
      id: "canines",
      front: "canines",
      back: "L: anterior region of the mouth, on both the upper and lower jaws just behind the\nincisors.\nF: used for biting, ripping, and tearing food.",
    },
    {
      id: "pharynx",
      front: "pharynx",
      back: "L: posterior to the mouth and nasal cavities.\nF: common passageway for the food and respiratory canals.",
    },
    {
      id: "epiglottis",
      front: "epiglottis",
      back: "L: cone-shaped flap in the back of the throat at the base of the tongue, just above\nthe larynx.\nF: folds over the glottis during swallowing to prevent food and liquids from\nentering the trachea.",
    },
    {
      id: "glottis",
      front: "glottis",
      back: "L: in the pharynx at the back of the throat, behind the epiglottis.\nF: passageway for air, connecting the pharynx to the larynx and trachea.",
    },
    {
      id: "esophagus",
      front: "esophagus",
      back: "L: posterior and dorsal to the glottis\nF: connects the oral cavity to the stomach, transporting food and liquid from pharynx to the stomach through muscle contractions in a process called peristalsis.",
    },
    {
      id: "thymus",
      front: "thymus",
      back: "L: in the thoracic cavity above the heart and in the neck along the trachea; throat\narea.\nF: produces antibodies for developing defense and immunity against disease.",
    },
    {
      id: "larynx",
      front: "larynx",
      back: "L: throat region, superior to the trachea and below the epiglottis.\nF: allows the pig to produce sounds, helps with breathing, and works with the\nepiglottis to close off the airway during swallowing.",
    },
    {
      id: "diaphragm",
      front: "diaphragm",
      back: "L: at the base of the ribcage\nF: separates the thoracic and the abdominal cavity.",
    },
    {
      id: "stomach",
      front: "stomach",
      back: "L: upper left quadrant of the abdominal cavity, beneath the liver.\nF: initiates the breakdown of nutrients using gastric acids.",
    },
    {
      id: "mucosa-innermost-one-of-the-three-layers-of-the-stomach",
      front: "mucosa (innermost one of the three layers of the stomach)",
      back: "F: secretes mucus that lubricates and protects the cells from digestive enzymes;\nsurface is covered with folds called rugae, which allow the stomach to expand\nafter a large meal.",
    },
    {
      id: "submucosa-layer-between-the-mucosa-and-muscularis-in-the-sto",
      front: "submucosa (layer between the mucosa and muscularis in the stomach)",
      back: "F: has blood vessels, nerves, and connective tissue that support and coordinate\nstomach activity.\n**note: stomach is protected by digesting itself because the secreted mucus is\nalkaline. if the protective system fails, then there will be a hole in the stomach\nlining (ulcer)",
    },
    {
      id: "muscularis-outermost-layer-of-the-stomach",
      front: "muscularis (outermost layer of the stomach)",
      back: "L: upper left portion of the abdominal cavity, right under the diaphragm.\nF: contracts and relaxes to mechanically churn food and move it through the\ndigestive tract via peristalsis.",
    },
    {
      id: "pylorus",
      front: "pylorus",
      back: "L: posterior end of the stomach.\nF: controls the flow of food and partially digested matter (chyme) from the\nstomach to the first part of the small intestine (duodenum)\n**note: pyloric sphincter is the passageway that controls the flow of substances\nbetween the stomach and the small intestine)",
    },
    {
      id: "mesentery",
      front: "mesentery",
      back: "L: thin, translucent membrane that anchors the coiled small intestine to the back\nwall of the abdominal cavity.\nF: connects organs like the spleen to the stomach and holds them in place, while\nacting as a pathway for blood vessels, nerves, and lymphatic vessels.",
    },
    {
      id: "spleen",
      front: "spleen",
      back: "L: on the left side of the abdominal cavity, above the pancreas.\nF: produces, stores, and eliminates red blood cells, while also producing white\nblood cells.",
    },
    {
      id: "small-intestine",
      front: "small intestine",
      back: "L: lower abdominal cavity directly below the stomach\nF: absorbs most of the nutrients from food into the bloodstream.",
    },
    {
      id: "duodenum",
      front: "duodenum",
      back: "L: uppermost section of the small intestine that connects directly to the stomach.\nF: receives chyme from the stomach and bile and pancreatic juices from the liver\nand pancreas- breaks down and absorbs proteins, fats, and carbs.",
    },
    {
      id: "jejunum",
      front: "jejunum",
      back: "L: middle section of the small intestine in between the duodenum and the ileum.\nF: further breaks down digested food and absorbs vital nutrients and water into\nthe bloodstream.\n**note: its b on the diagram pic**",
    },
    {
      id: "ileum",
      front: "ileum",
      back: "L: longest and most coiled section of the small intestine.\nF: completes the absorption of nutrients and bile salts and vitamin B12.\n**note: its c on the diagram pig**",
    },
    {
      id: "bile-duct",
      front: "bile duct",
      back: "L: tube that runs underside of the liver/gallbladder to the small intestine.\nF: transports bile from the gallbladder to the duodenum of the small intestine.",
    },
    {
      id: "gall-bladder",
      front: "gall bladder",
      back: "L: on the underside of the liver, tucked beneath the right median lobe.\nF: stores and concentrates bile, which is produced by the liver.",
    },
    {
      id: "pancreas",
      front: "pancreas",
      back: "L: in the abdominal cavity, dorsal to the stomach and within the curve of the\nduodenum.\nF: secretes digestive enzymes and sodium bicarbonate into the small intestine,\nand produces hormones like insulin and glucagon which are essential for regulating blood glucose levels.",
    },
    {
      id: "large-intestine",
      front: "large intestine",
      back: "L: posterior to the stomach and small intestine.\nF: absorbs water from undigested food, houses symbiotic bacteria, and prepares\nwaste for excretion.",
    },
    {
      id: "villi",
      front: "villi",
      back: "L: line the interior walls of the jejunum and ileum.\nF: maximize the surface area available to absorb nutrients and water.",
    },
    {
      id: "goblet-cells",
      front: "goblet cells",
      back: "L: throughout the mucosal lining of the small intestine, lines each villus.\nF: secrete mucus that acts as a lubricating layer that shield the intestinal walls,\nprevents friction, and aids in the passage of digestive materials.",
    },
    {
      id: "microvilli",
      front: "microvilli",
      back: "L: on villi\nF: further increase the cell surface area to maximize absorption of nutrients.",
    },
    {
      id: "caecum",
      front: "caecum",
      back: "L: blind-ended sac on the lower left side of the abdominal cavity.\nF: absorbs remaining water and salts from digested food before the waste moves\ninto the colon; also houses specialized bacteria to break down plant fibers like\ncellulose.",
    },
    {
      id: "rectum",
      front: "rectum",
      back: "L: posterior end of the large intestine, leading to the anus.\nF: stores and moves waste towards anus for removal.",
    },
    {
      id: "vocal-cords",
      front: "vocal cords",
      back: "L: inside the larynx.\nF: vibrate to produce sound.\n**note: if the tension is high, the pig will squeal. if the tension is low, the pig will\ngrunt.**",
    },
    {
      id: "trachea",
      front: "trachea",
      back: "L: tube in the throat, running from the larynx down to the lungs.\nF: serves as an open passageway for air into and out of the lungs.",
    },
    {
      id: "thyroid",
      front: "thyroid",
      back: "L: in the neck, on the ventral (belly) side of and posterior to the trachea.\nF: produces thyroxin, a hormone regulating metabolism.",
    },
    {
      id: "right-and-left-pleural-cavities",
      front: "right and left pleural cavities",
      back: "L: in the thorax, housing the lungs.\nF: compartmentalize the lungs and secrete lubricating fluid.",
    },
    {
      id: "lungs",
      front: "lungs",
      back: "F: exchange oxygen and carbon dioxide",
    },
    {
      id: "pericardial-cavity",
      front: "pericardial cavity",
      back: "L: fluid-filled space surrounding the heart.\nF: houses the heart",
    },
    {
      id: "heart",
      front: "heart",
      back: "F: pumps blood throughout the circulatory system, delivers nutrients and oxygen,\nremoves waste.",
    },
    {
      id: "bronchi",
      front: "bronchi",
      back: "L: branching tubes that connect the trachea to the lungs.\nF: passageways that conduct and distribute air into the right and left lungs.",
    },
    {
      id: "air-sacs",
      front: "air sacs",
      back: "L: deep inside the lungs, on either side of the heart.\nF: tiny sacs in the lungs that contain alveoli, where gas exchange takes place.\n**sidenote: sorry about the bird pic i couldn't find a pig one**",
    },
    {
      id: "alveoli",
      front: "alveoli",
      back: "L: at the very ends of the bronchioles in the lungs.\nF: facilitate the exchange of gases between the external air and the blood.",
    },
    {
      id: "arterioles",
      front: "arterioles",
      back: "F: connect larger arteries to capillary beds.",
    },
    {
      id: "capillaries",
      front: "capillaries",
      back: "F: facilitate the exchange of oxygen, nutrients, and waste between the blood and\nthe tissues.",
    },
    {
      id: "venules",
      front: "venules",
      back: "L: connecting capillaries to larger veins.\nF: collect deoxygenated blood and waste from the tissues and channel it into\nlarger veins to be returned to the heart and placenta.",
    },
    {
      id: "pericardium",
      front: "pericardium",
      back: "L: medial in the thoracic cavity, between the lungs.\nF: tough, protective membrane surrounding the heart.",
    },
    {
      id: "left-ventricle",
      front: "left ventricle",
      back: "L: lower left chamber of the heart.\nF: pumps oxygenated blood through the aorta to the rest of the body.",
    },
    {
      id: "right-ventricle",
      front: "right ventricle",
      back: "L: lower right chamber of the heart.\nF: pumps deoxygenated blood away from the heart.",
    },
    {
      id: "left-atrium",
      front: "left atrium",
      back: "L: flap on the top left side of the heart.\nF: collects oxygen-rich blood from the lungs and pumps it down to the left\nventricle.",
    },
    {
      id: "right-atrium",
      front: "right atrium",
      back: "L: flap on the top right side of the heart.\nF: receives deoxygenated blood returned from the pig's body and pumps it into\nthe right ventricle.",
    },
    {
      id: "pulmonary-trunk",
      front: "pulmonary trunk",
      back: "L: ventral surface of the heart.\nF: routes deoxygenated blood out of the heart through the pulmonary arteries.",
    },
    {
      id: "pulmonary-arteries",
      front: "pulmonary arteries",
      back: "F: carries deoxygenated blood to the lungs where it will release CO2 and pick up\nO2.",
    },
    {
      id: "aorta",
      front: "aorta",
      back: "F: leaves the left ventricle and carries the newly oxygenated blood to the body.",
    },
    {
      id: "ductus-arteriosus",
      front: "ductus arteriosus",
      back: "L: vessel that leads from the pulmonary trunk to the aorta.\nF: shunts blood away from the pulmonary circulation, which is not functional\nbefore birth.",
    },
    {
      id: "coronary-arteries",
      front: "coronary arteries",
      back: "L: run along the outside surface (epicardium) of the heart.\nF: deliver oxygenated, nutrient-rich blood to the thick myocardium of the heart\nitself, ensuring that the heart can pump blood.",
    },
    {
      id: "carotid-arteries",
      front: "carotid arteries",
      back: "L: in the neck, parallel to both sides of the trachea.\nF: transport oxygenated blood from the heart to the brain, neck, and face.",
    },
    {
      id: "left-subclavian-artery",
      front: "left subclavian artery",
      back: "L: second large branch off the aortic arch, to the left of the brachiocephalic trunk,\nand extends to the left forelimb.\nF: distributes nutrient-rich, oxygenated blood to the developing neck, thoracic\nwall, and forelegs.",
    },
    {
      id: "right-subclavian-artery",
      front: "right subclavian artery",
      back: "L: branches off the brachiocephalic trunk and extends to the right forelimb.\nF: distributes nutrient-rich, oxygenated blood to the developing neck, thoracic\nwall, and forelegs.",
    },
    {
      id: "aortic-arch",
      front: "aortic arch",
      back: "L: in the thoracic cavity directly on top of the heart.\nF: receives oxygenated blood from the left ventricle and distributes it to the head,\nneck and upper limbs.",
    },
    {
      id: "descending-aorta",
      front: "descending aorta",
      back: "L: along the dorsal midline of the body.\nF: carries oxygenated blood from the heart to the lower half of the body, eventually\nbranching into the umbilical arteries to exchange materials with the placenta.",
    },
    {
      id: "coelic-artery",
      front: "coelic artery",
      back: "L: first major branch of the abdominal aorta below the diaphragm.\nF: supplies oxygenated blood to the liver, stomach, spleen, and pancreas.",
    },
    {
      id: "mesenteric-artery",
      front: "mesenteric artery",
      back: "F: supplies oxygenated blood to the digestive tract, primarily the small and large\nintestines.",
    },
    {
      id: "renal-arteries",
      front: "renal arteries",
      back: "L: paired blood vessels that branch off the abdominal aorta.\nF: carry blood directly into the left and right kidneys, where the kidneys filter\nmetabolic waste from the blood.",
    },
    {
      id: "iliac-arteries",
      front: "iliac arteries",
      back: "L: branch off near the posterior end of the aorta.\nF: supply blood to the pelvic region and each leg.",
    },
    {
      id: "umbilical-arteries",
      front: "umbilical arteries",
      back: "L: lower abdominal/pelvic cavity, branching off the iliac arteries.\nF: carry deoxygenated blood from the fetal pig to the placenta.",
    },
    {
      id: "atrioventricular-valves",
      front: "atrioventricular valves",
      back: "L: between each atrium and ventricle.\nF: permits the one-way flow of blood from the atria to the ventricles and prevents\nthe backflow of blood when the ventricles contract.",
    },
    {
      id: "semilunar-valves",
      front: "semilunar valves",
      back: "L: at the entrance of the pulmonary artery and the aorta.\nF: permits the forward flow of blood while snapping shut to prevent dangerous\nbackflow into the ventricles when the heart relaxes.",
    },
    {
      id: "umbilical-vein",
      front: "umbilical vein",
      back: "F: carries blood rich in oxygen and food materials and low in waste from the\nplacenta to the fetal pig.",
    },
    {
      id: "caudal-inferior-posterior-vena-cava",
      front: "caudal/inferior/posterior vena cava",
      back: "L: runs along the dorsal wall of the abdominal cavity.\nF: transports deoxygenated blood from the lower body and oxygenated blood\nfrom the placenta to the right atrium of the heart.",
    },
    {
      id: "foramen-ovale",
      front: "foramen ovale",
      back: "L: oval shaped opening in the interatrial septum, the wall that divides the right and\nleft atria.\nF: bypasses the non-functional fetal lungs.",
    },
    {
      id: "cranial-superior-anterior-vena-cava",
      front: "cranial/superior/anterior vena cava",
      back: "L: vessel entering the top of the heart.\nF: collects deoxygenated blood from the upper half of hte body and returns it to\nthe right atrium.",
    },
    {
      id: "pulmonary-veins",
      front: "pulmonary veins",
      back: "F: carry oxygenated blood from the lungs back to the left atrium of the heart.",
    },
    {
      id: "kidneys",
      front: "kidneys",
      back: "F: filter waste products, excess water, and salts from the blood to produce urine,\nmaintaining the body's internal balance.",
    },
    {
      id: "renal-hilum",
      front: "renal hilum",
      back: "L: concave indentation on the medial (inner) side of the kidney.\nF: it is where the blood vessels and ureter are attached.",
    },
    {
      id: "renal-artery",
      front: "renal artery",
      back: "L: branches off the abdominal aorta and extends laterally into the hilum of each\nkidney.\nF: carries blood from the aorta to the kidney.\n**note: i think its c on the diagram**",
    },
    {
      id: "renal-vein",
      front: "renal vein",
      back: "F: blood vessel that carries blood from the kidneys to the posterior vena cava.\n**note: d on diagram**",
    },
    {
      id: "ureter",
      front: "ureter",
      back: "L: pair of two muscular tubes.\nF: carries urine from the kidney to the urinary bladder.",
    },
    {
      id: "renal-medulla",
      front: "renal medulla",
      back: "L: innermost layer of the kidney.\nF: regulates the concentration and volume of urine.",
    },
    {
      id: "renal-pelvis",
      front: "renal pelvis",
      back: "L: funnel-shaped cavity inside kidney.\nF: stores urine before it enters the ureter.",
    },
    {
      id: "renal-cortex",
      front: "renal cortex",
      back: "L: dense, light colored outer layer of the kidney.\nF: contains nephrons which filter metabolic wastes, water, and ions from the\nblood.",
    },
    {
      id: "nephrons",
      front: "nephrons",
      back: "L: inside the kidneys\nF: filter blood, reabsorb useful nutrients and water, and excrete waste products to\nregulate fluid and electrolyte balance.",
    },
    {
      id: "glomerulus",
      front: "glomerulus",
      back: "L: in the renal cortex, inside the Bowman's capsule.\nF: filtration barrier that filters waste, excess water, and salts out of the blood to\ninitiate urine formation.\n**note: it is A on the picture**",
    },
    {
      id: "bowman-s-capsule",
      front: "Bowman's capsule",
      back: "L: in the renal cortex.\nF: encloses the glomerulus and captures waste-filled fluid filtered from the blood\nduring the first step of urine formation.\n**note: it is B on the picture**",
    },
    {
      id: "proximal-convoluted-tubule",
      front: "proximal convoluted tubule",
      back: "L: in the renal cortex.\nF: has microvilli for reabsorption of useful nutrients, water, and ions back into the\nblood; also secretes some waste into the filtrate.",
    },
    {
      id: "loop-of-henle",
      front: "loop of Henle",
      back: "L: in the renal medulla.\nF: reabsorbs water and ions from the urine to maintain body's water balance and\nconcentrate urine.",
    },
    {
      id: "distal-convoluted-tubule",
      front: "distal convoluted tubule",
      back: "L: in the renal cortex.\nF: fine-tunes electrolyte, acid-base balance, and the pH by selectively reabsorbing\nsalts and water followed by osmosis.",
    },
    {
      id: "collecting-ducts",
      front: "collecting ducts",
      back: "L: inside the kidneys, starting in the renal cortex, passing through the medulla,\nand funneling into the renal pelvis.\nF: this is where the final reabsorption of water occurs before channeling the fluid\ninto the ureters and the bladder.",
    },
    {
      id: "urinary-bladder",
      front: "urinary bladder",
      back: "L: in between the two umbilical arteries.\nF: temporarily stores urine filtered by the kidneys before it is excreted.",
    },
    {
      id: "urethra",
      front: "urethra",
      back: "L: posterior from the bladder.\nF: carries the urine to the exterior.",
    },
    {
      id: "ovaries",
      front: "ovaries",
      back: "L: in the abdominal cavity, posterior to the kidneys and dorsal to the intestines.\nF: produce and stores the female eggs, and produce and release reproductive\nhormones like estrogen and progesterone into the bloodstream.",
    },
    {
      id: "oviduct-aka-fallopian-tube",
      front: "oviduct aka fallopian tube",
      back: "L: tubes connecting the ovaries and the uterine horns.\nF: pathway for eggs to travel from the ovaries to the uterus, and is the site of\nfertilization.",
    },
    {
      id: "uterus",
      front: "uterus",
      back: "L: in the lower abdominal/pelvic cavity, dorsal to the urinary bladder ad urethra.\nF: place where the eggs implant and develop; protects the fetus as it grows and\ncontracts to deliver the baby.\n**note: it is specially adapted to support large litters**",
    },
    {
      id: "endometrium",
      front: "endometrium",
      back: "L: innermost lining of the uterus.\nF: supports embryo implantation and secretes nutrient-rich fluids to nourish\ndeveloping piglets.",
    },
    {
      id: "placenta",
      front: "placenta",
      back: "L: temporary organ in the mother's uterus.\nF: facilitates exchange of nutrients, oxygen, and metabolic wastes between the\nmother's bloodstream and the developing fetus.",
    },
    {
      id: "uterine-horns",
      front: "uterine horns",
      back: "L: lower abdominal and pelvic cavity.\nF: primary site of fetal development and it can accommodate multiple embryos\nsimultaneously.",
    },
    {
      id: "vagina",
      front: "vagina",
      back: "L: dorsal to the urethra and ventral to the rectum.\nF: acts as the birth canal during delivery and receives sperm during mating.",
    },
    {
      id: "cervix",
      front: "cervix",
      back: "L: posterior end of the uterus and connecting to the vagina.\nF: a sphincter muscle that acts as a physical barrier between the external and\ninternal reproductive tracts; helps protect the uterus and dilates during childbirth.",
    },
    {
      id: "vas-deferens",
      front: "vas deferens",
      back: "L: tube from epididymis to pelvic cavity.\nF: ducts that transport mature sperm away from the testes and epididymis toward\nthe urethra to be expelled from the body.",
    },
    {
      id: "testes",
      front: "testes",
      back: "F: produce sperm cells and secrete male sex hormones, especially testosterone.",
    },
    {
      id: "inguinal-canals",
      front: "inguinal canals",
      back: "L: in the lower abdominal wall, just above the groin.\nF: allow the testes and other structures to descend from the abdominal cavity\ndown into the scrotum.",
    },
    {
      id: "seminal-vesicles",
      front: "seminal vesicles",
      back: "L: on the dorsal surface of the male pig's pelvic region.\nF: secrete a fluid that makes up the bulk of seminal plasma, containing nutrients\nand buffers.",
    },
    {
      id: "prostate",
      front: "prostate",
      back: "L: between the bladder and urethra.\nF: supplies milky secretions that, together with the sperm, make up the semen\nwhich neutralizes the acidic environment of the female reproductive tract.",
    },
    {
      id: "hormones",
      front: "hormones",
      back: "F: carry chemical messages to some distant part of the body where they alter\ncellular activity.",
    },
    {
      id: "thyroxine",
      front: "thyroxine",
      back: "F: produced by the thyroid gland, and speeds up cellular metabolism.",
    },
    {
      id: "calcitonin",
      front: "calcitonin",
      back: "F: produced by the thyroid gland, and decreases calcium levels by causing the\ndeposition of calcium in the bone.",
    },
    {
      id: "parathyroid-glands",
      front: "parathyroid glands",
      back: "L: four glands located on the thyroid in the neck.\nF: produce parathyroid hormone (PTH- increases calcium levels in the blood by\nreleasing calcium from the bones.)",
    },
    {
      id: "adrenal-glands",
      front: "adrenal glands",
      back: "L: medially near the abdominal aorta, anterior to the top end of the kidneys.\nF: produce hormones like epinephrine, cortisol, and norepinephrine that control\nblood pressure and metabolism.",
    },
    {
      id: "adrenal-medulla",
      front: "adrenal medulla",
      back: "L: innermost core of the adrenal glands.\nF: secrete fight-or-flight hormones like adrenaline and noradrenaline to regulate\nstress responses, blood pressure, and heart rate.",
    },
    {
      id: "adrenal-cortex",
      front: "adrenal cortex",
      back: "L: outer region of adrenal glands.\nF: secretes steroid hormones that mobilize energy reserves in times of prolonged\nstress, maintain the level of sodium ions in the blood, etc.",
    },
    {
      id: "islets-of-langerhans",
      front: "islets of Langerhans",
      back: "L: scattered throughout the pancreas\nF: monitor blood sugar levels and release hormones, especially insulin and\nglucagon, directly into the bloodstream to maintain glucose homeostasis.\n**note: insulin lowers blood sugar, while glucagon raises it.**",
    },
    {
      id: "relaxin-a-hormone",
      front: "relaxin (a hormone)",
      back: "F: facilitates both fertilization and the birth process.",
    },
    {
      id: "pineal-gland",
      front: "pineal gland",
      back: "L: in the center of the brain.\nF: produces melatonin (prepares animals for the changing seasons, and also\ninfluences mating behavior and reproduction)",
    },
    {
      id: "hypothalamus",
      front: "hypothalamus",
      back: "L: at the base of the brain, below the thalamus and above the pituitary gland.\nF: releases hormones that control the output of several hormones from the\npituitary gland; links the nervous and endocrine systems.",
    },
    {
      id: "pituitary-gland",
      front: "pituitary gland",
      back: "L: base of the brain.\nF: releases essential hormones and controls other glands.",
    },
    {
      id: "eyeball",
      front: "eyeball",
      back: "F: detects light and converts it into nerve signals that are sent to the brain for visual\nprocessing.",
    },
    {
      id: "orbit-in-the-eye",
      front: "orbit (in the eye)",
      back: "L: conical socket located on the lateral sides of the skull, anterior to the ear flaps.\nF: houses, protects, and supports the eyeball, optic nerve, extraocular muscles,\nand surrounding glandular structures.",
    },
    {
      id: "lacrimal-tear-glands",
      front: "lacrimal (tear) glands",
      back: "L: upper-outer angle of the eye's orbit.\nF: produce and secrete the fluid (tears) that cleans, nourishes, and lubricates the\neye.",
    },
    {
      id: "extrinsic-ocular-muscles",
      front: "extrinsic ocular muscles",
      back: "L: outside the eyeball within the eye socket.\nF: six of them move the eyeball itself in various directions, while the seventh one,\nthe levator palpebrae superioris, elevates the upper eyelid; connect the eyeball to\nthe orbit and control the eye's movements.",
    },
    {
      id: "optic-nerve",
      front: "optic nerve",
      back: "L: connects retina to the brain.\nF: carries visual information from the eye to the brain's visual cortex for processing.",
    },
    {
      id: "fibrous-tunic",
      front: "fibrous tunic",
      back: "L: tough, outermost layer of the eyeball.\nF: provides structural support, maintains the eye shape, and protects the delicate\ninner tissues.",
    },
    {
      id: "sclera",
      front: "sclera",
      back: "L: tough, white, outer layer of the eyeball.\nF: acts as a strong protective shield for the delicate internal structures of the\neye and provides a sturdy attachment point for the muscles that control eye\nmovement.",
    },
    {
      id: "cornea",
      front: "cornea",
      back: "L: front of the eye, anterior to the iris and pupil.\nF: protective barrier and the eye's primary reflective surface that bends light to\nfocus it into the lens.",
    },
    {
      id: "vascular-tunic",
      front: "vascular tunic",
      back: "L: middle layer of the eyeball, located between the fibrous tunic and the retina.\nF: nourishes the eye, regulates how much light can enter, and focuses the lens;\nconsists of the choroid, ciliary body, and iris.",
    },
    {
      id: "choroid",
      front: "choroid",
      back: "L: in the vascular tunic.\nF: has blood vessels that supply oxygen and nutrients to the retina; its dark\npigmentation absorbs stray light rays, preventing light from bouncing around\ninside the eye and ensuring sharp, clear vision.",
    },
    {
      id: "lens",
      front: "lens",
      back: "L: behind the iris and pupil and in front of the vitreous humor.\nF: focuses incoming light, fine-tunes the image to project it sharply onto the retina.",
    },
    {
      id: "iris",
      front: "iris",
      back: "L: middle of the eyeball, between the cornea and lens.\nF: adjusts the size of the pupil, controlling the amount of light that enters the eye.",
    },
    {
      id: "pupil",
      front: "pupil",
      back: "L: dark, circular opening in the center of the iris.\nF: regulates the amount of light passing through the lens.",
    },
    {
      id: "ciliary-body",
      front: "ciliary body",
      back: "L: ridged ring of tissue located behind in the iris.\nF: produces aqueous humor and changes the shape of the lens, permitting sharp\nfocusing.",
    },
    {
      id: "retina",
      front: "retina",
      back: "L: innermost layer of tissue at the back of the eyeball.\nF: made of rods and cones, detects light, converts those light rays into electrical\nand chemical signals, and sends them to the brain via the optic nerve to form\nimages.",
    },
    {
      id: "retinal-rods",
      front: "retinal rods",
      back: "L: in the retina at the back of the eye.\nF: enable vision in dim, low-light conditions and detects shapes and movement,\nthough they do not process color.",
    },
    {
      id: "retinal-cones",
      front: "retinal cones",
      back: "L: in the retina.\nF: detect color and enable sharp, detailed vision in bright light.",
    },
    {
      id: "photoreceptor-cells",
      front: "photoreceptor cells",
      back: "L: in the retina.\nF: convert incoming light into electrical neural signals which are then transmitted\nto the brain to form visual images.",
    },
    {
      id: "vitreous-humor",
      front: "vitreous humor",
      back: "L: viscous material between the retina and lens.\nF: acts a shock absorber and maintains the eye's spherical shape, ensuring the\nretina stays securely in place.",
    },
    {
      id: "aqueous-humor",
      front: "aqueous humor",
      back: "L: fluid that fills the anterior chamber (between the iris and cornea) and posterior\nchamber (between the iris and lens) of the eye.\nF: maintains intraocular pressure to give the eyeball its shape and supplies\nessential nutrients to the eye's avascular structures.",
    },
    {
      id: "middle-ear-tympanic-cavity",
      front: "middle ear/tympanic cavity",
      back: "L: inside the temporal bone, medial to the tympanic membrane.\nF: transmits and amplify sound vibrations from the outer ear to the fluid-filled\ninner ear, while using the Eustachian tube to equalize pressure.",
    },
    {
      id: "ossicles",
      front: "ossicles",
      back: "L: middle ear\nF: transmits and amplifies sound vibrations from the eardrum to the inner ear.",
    },
    {
      id: "malleus-hammer",
      front: "malleus (hammer)",
      back: "L: ossicle that is closest to the eardrum.\nF: moves after sensing a vibration in the eardrum, and then transfers this mechanical energy to in the incus.",
    },
    {
      id: "incus-anvil",
      front: "Incus (anvil)",
      back: "L: behind the malleus; middle one of the ossicles.\nF: mechanically transmits sound vibrations from the malleus to the stapes so they\ncan reach the inner ear.",
    },
    {
      id: "stapes-stirrup",
      front: "stapes (stirrup)",
      back: "L: innermost ossicle, linking the incus to the oval window of the inner ear.\nF: transmits and amplifies sound vibrations, pushing against the fluid-filled inner\near (oval window) to convert mechanical vibrations into fluid waves that the brain\ninterprets as sound.",
    },
    {
      id: "oval-window-aka-fenestra-vestibuli",
      front: "oval window aka fenestra vestibuli",
      back: "L: in the middle ear, on the medial wall of the middle ear cavity, separating it from\nthe inner ear.\nF: transmits sound vibrations from the ossicles into the cochlear fluid in the inner\near, converting them into nerve signals the brain interprets as sound.",
    },
    {
      id: "round-window-aka-fenestra-cochlea",
      front: "round window aka fenestra cochlea",
      back: "L: on the medial wall of the middle ear, just inferior and slightly posterior to the\noval window.\nF: acts as a pressure release valve for the fluid inside the cochlea, which allows\nsound waves to travel through the inner ear.",
    },
    {
      id: "cochlea",
      front: "cochlea",
      back: "L: in temporal bone of the skull, which forms part of the inner ear.\nF: converts sound wave vibrations into electrical nerve impulses that are sent to\nthe brain to be interpreted; responsible for hearing.",
    },
    {
      id: "meninges",
      front: "meninges",
      back: "L: between the central nervous system and the skull or vertebrae.\nF: provides a physical cushion, anchors the brain so it doesn't jostle inside the\nskull, and supports blood vessels and cerebrospinal fluid.",
    },
    {
      id: "pia-mater",
      front: "pia mater",
      back: "L: innermost layer of the meninges\nF: protects and supports the tissues, carries tiny blood vessels that nourish the\nbrain and spinal cord tissue, and helps contain the cerebrospinal fluid which\nallows for waste removal.",
    },
    {
      id: "arachnoid-membrane",
      front: "arachnoid membrane",
      back: "L: middle layer of the meninges, between the outer dura mater and the inner pia\nmater.\nF: protects the CNS by acting as a shock absorber and providing a space for\ncushioning fluids.",
    },
    {
      id: "cerebrospinal-fluid",
      front: "cerebrospinal fluid",
      back: "L: inside the brain, central canal of the spinal cord, and surrounding subarachnoid\nspace.\nF: mechanically cushions the brain and spine against shock, provides buoyancy,\ntransports nutrients, and removes waste products.",
    },
    {
      id: "dura-mater",
      front: "dura mater",
      back: "L: lines the inside of the skull and surrounds the spinal cord.\nF: provides a durable, protective, and supportive physical barrier for the delicate\nbrain and CNS.",
    },
    {
      id: "cerebrum",
      front: "cerebrum",
      back: "L: largest and most anterior part of hte brain, beneath the frontal bones of the\nskull.\nF: interprets information from the senses, initiates and coordinates voluntary\nmuscle movements, is responsible for memory, reasoning and thought processes.",
    },
    {
      id: "cerebral-hemispheres",
      front: "cerebral hemispheres",
      back: "L: in the skull, identified by a deep central groove called the longitudinal fissure.\nF: control center for higher-level functions, sensory processing, motor control,\ncognition.",
    },
    {
      id: "gyri",
      front: "gyri",
      back: "L: folds and bumps on the surface of the cerebrum.\nF: increase the brain's surface area, allowing for more neurons and greater\ncognitive capacity to fit inside a limited skull space.",
    },
    {
      id: "sulci",
      front: "sulci",
      back: "L: grooves found on the highly folded outer surface of the cerebrum.\nF: increases surface area of the cerebral cortex, divides the cerebrum into distinct\nlobes (frontal, temporal, occipital, parietal)",
    },
    {
      id: "rhinecephalon",
      front: "rhinecephalon",
      back: "L: below the cerebrum.\nF: processes for the sense of smell, receiving sensory data directly from the\nnasal cavity, and integrates the olfactory information with instinctive behaviors like\nfeeding and reproduction.",
    },
    {
      id: "olfactory-bulb",
      front: "olfactory bulb",
      back: "L: anterior part of the rhinecephalon.\nF: receives and processes sensory information about smells; brain's first relay\nstation for odor signals, taking input directly from the nasal cavity and passing\nit along to higher levels of the brain to help the animal interpret the environment.",
    },
    {
      id: "olfactory-nerve",
      front: "olfactory nerve",
      back: "F: transmits odor data from the nasal mucosa (roof) directly to the olfactory bulbs\nof the brain, allowing the animal to perceive scents.",
    },
    {
      id: "pons",
      front: "pons",
      back: "L: brainstem, between the midbrain and the medulla oblongata.\nF: acts as a conduction and relay center, regulating breathing rhythm and transmitting signals between the cerebrum, cerebellum, and spinal cord.",
    },
    {
      id: "medulla-oblongata",
      front: "medulla oblongata",
      back: "L: lowest part of the brainstem, located at the base of the skull where the brain\nmeets the spinal cord.\nF: regulates many visceral activities such as rate of heart rate, blood pressure,\nbreathing movements, etc.",
    },
    {
      id: "eustachian-tube",
      front: "eustachian tube",
      back: "L: in the nasopharynx (upper part of the throat, dorsal to the soft palate).\nF: connects the middle ear cavity to the pharynx, equalizing air pressure and\ndraining fluids.",
    },
    {
      id: "semicircular-canals",
      front: "semicircular canals",
      back: "L: in the inner ear's bony labyrinth.\nF: senses rotational and angular head movements, which is essential for maintaining balance, equilibrium, and spatial orientation.",
    },
    {
      id: "parietal-pleura",
      front: "parietal pleura",
      back: "L: membrane that lines the inner walls of the thoracic cavity, the mediastinum, and\nsuperior surface of the diaphragm.\nF: secretes a lubricating fluid that allows the lungs to expand and contract smoothly against the chest wall without causing friction; helps seal and separate the heart\nin the central pericardial cavity.",
    },
  ],
};

export const decks: Deck[] = [pigAnatomyDeck];
